version: '3'
services:
  playground-web-db:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    networks:
      - node-network
    ports:
      - 27017:27017
  playground-web-frontend:
    image: sathvik04/tinder-clone:latest
    environment:
      PORT: 3000
      PROXY_API: http://tinder-server:8000/
    restart: always
    ports:
      - 3000:3000
  playground-web-backend:
    image: sathvik04/tinder-server:latest
    environment:
      URI: mongodb://playground-web-db:27017
    restart: always
    depends_on:
      - playground-web-db
    volumes:
      - .:/src
    networks:
      - node-network
    ports:
      - 8000:8000

volumes:
  mongodata:

networks:
  node-network:
    driver: bridge